version: 0.2

phases:
  install:
    commands:
      - echo Using Amazon Corretto 11 and Node.js
      - git clone https://github.com/flutter/flutter.git -b stable
      - export PATH="$PATH:`pwd`/flutter/bin"
      - flutter doctor
      - flutter precache
  build:
    commands:
      - echo Building Flutter APK...
      - flutter clean
      - flutter build apk --release
  post_build:
    commands:
      - echo Build complete.

artifacts:
  files:
    - build/app/outputs/flutter-apk/app-release.apk
  discard-paths: no