version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing Flutter SDK...
      - git clone https://github.com/flutter/flutter.git -b stable --depth 1
      - export PATH="$PATH:`pwd`/flutter/bin"
      - flutter doctor
  pre_build:
    commands:
      - echo Installing dependencies...
      - flutter pub get
  build:
    commands:
      - echo Building Flutter web app...
      - flutter build web --release
artifacts:
  files:
    - '**/*'
  base-directory: 'build/web*'