name: transaction_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.2

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bloc_test: ^9.1.7
  cached_network_image: ^3.4.0
  cloud_firestore: ^5.2.1
  confetti: ^0.7.0
  dartz: ^0.10.1
  device_preview: ^1.2.0
  firebase_analytics: ^11.2.1
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  firebase_performance: ^0.10.0+4
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_contacts: ^1.1.9+2
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  flutter_stripe: ^11.0.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.3
  http: ^1.2.2
  icons_plus: ^5.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  permission_handler: ^11.3.1
  phone_number: ^2.1.0
  plaid_flutter: ^3.1.8
  printing: ^5.13.1
  responsive_builder: ^0.7.1
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  simple_circular_progress_bar: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svgs/
    - .env
    

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
        - asset: assets/fonts/open_sans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/open_sans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
        - asset: assets/fonts/open_sans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
        - asset: assets/fonts/open_sans/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/open_sans/OpenSans-SemiBoldItalic.ttf

flutter_gen:
  colors:
    inputs:
      - assets/colors/color_pallet.xml

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"
  # adaptive_icon_foreground: "assets/icon/icon-foreground.png"